#to use trycloudflare comment out the enviroment key, the TUNNEL_TOKEN and the run under command.
#then uncomment the --url
#the subdomain where the site should be published will be on the make run-tunnel logs.
version: "0.2"
services:
  sirehp:
    container_name: sirehp
    build: .
    restart: unless-stopped
    volumes:
      - ./instance:/kerkoapp/instance
      - ./instance/logs:/dev/log
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    ports:
      - "42031:8080"
    command:
      - tunnel
      - run
#example using trycloudflare
#      - --url http://sirehp:80/bibliography
    env_file:
      - "instance/.env"