#to use trycloudflare comment out the env-file group and the run under command.
#then uncomment the --url
#the subdomain where the site should be published will be on the make run-tunnel logs.
services:
  sirehp:
    container_name: sirehp
    build: allfa/sirehp
    restart: unless-stopped
    volumes:
      - ./instance:/kerkoapp/instance
      - ./instance/logs:/dev/log
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    #example using trycloudflare
    #command: tunnel --url http://sirehp:80
    env_file:
      - "instance/.env"